# Setup
title: Horários
tagline: IFPB Campus Guarabira
baseurl: "/horarios"

# About/contact
author:
  name: Moisés Guimarães
  url: https://moisesguimaraes.github.io

# Others
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - csv_to_json.py
  - jekyll-cayman-theme.gemspec